"""update_models

Revision ID: 0b671f60a0e2
Revises: f243cb68d204
Create Date: 2026-04-08 19:40:51.156288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b671f60a0e2'
down_revision: Union[str, Sequence[str], None] = 'f243cb68d204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender', sa.String(length=120), nullable=False))
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('messages', 'sender')
    # ### end Alembic commands ###
